-- database/staging/create_transaction_info_stg.sql

CREATE TABLE TRANSACTIONINFO_STG(
	TRANSACTIONDATE		VARCHAR2(10),
	ACCOUNT_NUMBER		VARCHAR2(12),
	AMOUNT			VARCHAR2(8),
	TRANSACTION_TYPE	VARCHAR2(2)
);

