-- database/staging/create_account_requests_stg.sql

WHENEVER SQLERROR EXIT
SQL.SQLCODE

BEGIN
	EXECUTE IMMEDIATE 'DROP TABLE ACCOUNTREQUEST_STG PURGE';
	EXCEPTION WHEN OTHERS THEN
		IF SQLCODE != -942 THEN
			RAISE;
		END IF;
	END;
/
CREATE TABLE ACCOUNTREQUEST_STG(
	BRANCH		VARCHAR2(15),
	ACCOUNT_TYPE	VARCHAR2(15),
	TITLE		VARCHAR2(4),
	FIRSTNAME	VARCHAR2(15),
	LASTNAME	VARCHAR2(15),
	BIRTHDAY	VARCHAR2(10),
	WORKPHONE	VARCHAR2(10),
	HOMEPHONE	VARCHAR2(10),
	ADDRESS		VARCHAR2(30),
	STATE		VARCHAR2(15),
	ZIP		VARCHAR2(10),
	EMAIL		VARCHAR2(30)
);

EXIT;

