-- database/staging/drop_transaction_info.sql

SET SERVEROUTPUT ON
BEGIN
	EXECUTE IMMEDIATE 'DROP TABLE TRANSACTIONINFO_STG PURGE';
EXCEPTION WHEN OTHERS THEN
	DBMS_OUTPUT.PUT_LINE('Could not drop staging table: ' || SQLERRM);
END;
/
EXIT;

