-- database/procedures/prc_load_transactions.sql

SET SERVEROUTPUT ON;

DECLARE
	V_EXISTS	NUMBER;
	V_INTEREST	NUMBER(10,4);
	V_INSERTED	NUMBER := 0;
	V_REJECTED	NUMBER := 0;
BEGIN
	FOR REC IN (SELECT * FROM TRANSACTIONINFO_STG) LOOP
		SELECT COUNT(*)
		INTO V_EXISTS
		FROM REGISTEREDINFO
		WHERE ACCOUNT_NUMBER = REC.ACCOUNT_NUMBER;

		IF V_EXISTS = 1 AND IS_VALID_DATE(REC.TRANSACTIONDATE) = 1 THEN
			V_INTEREST := CALCULATE_INTEREST(TO_NUMBER(REC.AMOUNT), REC.TRANSACTION_TYPE);

			INSERT INTO TRANSACTIONINFO(
				TRANSACTIONID,
				TRANSACTIONDATE,
				ACCOUNT_NUMBER,
				AMOUNT,
				INTEREST,
				TRANSACTION_TYPE
			) VALUES(
				TRANS_ID_SEQ.NEXTVAL,
				TO_DATE(REC.TRANSACTIONDATE, 'DD/MM/YYYY'),
				REC.ACCOUNT_NUMBER,
				TO_NUMBER(REC.AMOUNT),
				V_INTEREST,
				REC.TRANSACTION_TYPE
			);

			V_INSERTED := V_INSERTED + 1;
		ELSE
			IF V_EXISTS = 0 THEN
				DBMS_OUTPUT.PUT_LINE('Rejected Account: ' || REC.ACCOUNT_NUMBER);
			ELSE
				DBMS_OUTPUT.PUT_LINE('Rejected Date: ' || REC.TRANSACTIONDATE);
			END IF;

			V_REJECTED := V_REJECTED + 1;
		END IF;
	END LOOP;

	COMMIT;

	DBMS_OUTPUT.PUT_LINE('Transaction Load Completed Successfully.');
	DBMS_OUTPUT.PUT_LINE('Records Inserted: ' || V_INSERTED);
	DBMS_OUTPUT.PUT_LINE('Records Rejected: ' || V_REJECTED);

END;
/

