-- database/procedures/prc_load_transactions.sql

SET SERVEROUTPUT ON;

DECLARE
	V_EXISTS	NUMBER;
	V_INTEREST	NUMBER(10,4);
	V_INSERTED	NUMBER := 0;
	V_REJECTED	NUMBER := 0;
	V_REASON	VARCHAR2(300);
BEGIN
	DELETE FROM TRANSACTIONINFO_REJECTED;
	FOR REC IN (SELECT * FROM TRANSACTIONINFO_STG) LOOP
		SELECT COUNT(*)
		INTO V_EXISTS
		FROM REGISTEREDINFO
		WHERE ACCOUNT_NUMBER = REC.ACCOUNT_NUMBER;
		
		V_REASON := NULL;

		IF REC.TRANSACTION_TYPE NOT IN ('TR', 'LN') THEN
			DBMS_OUTPUT.PUT_LINE('Rejected Transaction Type: ' || REC.TRANSACTION_TYPE);
			V_REJECTED := V_REJECTED + 1;
			V_REASON := 'Invalid Transaction Type; ';
		END IF;

		IF REC.AMOUNT IS NULL THEN
			DBMS_OUTPUT.PUT_LINE('Missing Amount');
			V_REJECTED := V_REJECTED + 1;
			V_REASON := V_REASON || 'Missing Amount; ';
		ELSIF TO_NUMBER(REC.AMOUNT) <= 0 THEN
			DBMS_OUTPUT.PUT_LINE('Rejected Amount: ' || REC.AMOUNT);
			V_REJECTED := V_REJECTED + 1;
			V_REASON := V_REASON || 'Invalid Amount; ';
		END IF;

		IF TRIM(REC.ACCOUNT_NUMBER) IS NULL THEN
			DBMS_OUTPUT.PUT_LINE('Missing Account Number');
			V_REJECTED := V_REJECTED + 1;
			V_REASON := V_REASON || 'Missing Account Number; ';
		END IF;

		IF V_REASON IS NULL AND V_EXISTS = 1 AND IS_VALID_DATE(REC.TRANSACTIONDATE) = 1 THEN
			V_INTEREST := CALCULATE_INTEREST(TO_NUMBER(REC.AMOUNT), REC.TRANSACTION_TYPE);

			INSERT INTO TRANSACTIONINFO(
				TRANSACTIONID,
				TRANSACTIONDATE,
				ACCOUNT_NUMBER,
				AMOUNT,
				INTEREST,
				TRANSACTION_TYPE
			) VALUES(
				TRANS_ID_SEQ.NEXTVAL,
				TO_DATE(REC.TRANSACTIONDATE, 'DD/MM/YYYY'),
				REC.ACCOUNT_NUMBER,
				TO_NUMBER(REC.AMOUNT),
				V_INTEREST,
				REC.TRANSACTION_TYPE
			);

			V_INSERTED := V_INSERTED + 1;
		ELSE
			IF V_EXISTS = 0 THEN
				DBMS_OUTPUT.PUT_LINE('Rejected Account: ' || REC.ACCOUNT_NUMBER);
				V_REASON := V_REASON || 'Invalid Account Number; ';
			ELSE
				DBMS_OUTPUT.PUT_LINE('Rejected Date: ' || REC.TRANSACTIONDATE);
				V_REASON := V_REASON || 'Invalid Date; ';
			END IF;
			V_REJECTED := V_REJECTED + 1;
		END IF;

		IF V_REASON IS NOT NULL THEN
			INSERT INTO TRANSACTIONINFO_REJECTED(
				TRANSACTIONDATE,
				ACCOUNT_NUMBER,
				AMOUNT,
				TRANSACTION_TYPE,
				REJECT_REASON
			) VALUES(
				REC.TRANSACTIONDATE,
				REC.ACCOUNT_NUMBER,
				REC.AMOUNT,
				REC.TRANSACTION_TYPE,
				RTRIM(V_REASON, '; ')
			);
		END IF;
	END LOOP;

	COMMIT;

	DBMS_OUTPUT.PUT_LINE('Transaction Load Completed Successfully.');
	DBMS_OUTPUT.PUT_LINE('Records Inserted: ' || V_INSERTED);
	DBMS_OUTPUT.PUT_LINE('Records Rejected: ' || V_REJECTED);

END;
/

