-- database/procedures/prc_approve_accounts.sql

SET SERVEROUTPUT ON;

DECLARE
	V_ACCOUNT_NUMBER	VARCHAR2(12);
	V_NEXT_SEQ		NUMBER;
	V_PROCESSED		NUMBER := 0;
	V_REGISTERED		NUMBER;
BEGIN
	FOR REC IN (
		SELECT * FROM ACCOUNTREQUEST 
		WHERE STATUS = 'Entered'
		ORDER BY REQUESTID)
	LOOP
		BEGIN
			SELECT COUNT(*)
			INTO V_REGISTERED
			FROM REGISTEREDINFO
			WHERE UPPER(FIRSTNAME) = UPPER(REC.FIRSTNAME) AND UPPER(LASTNAME) = UPPER(REC.LASTNAME) AND BIRTHDAY = REC.BIRTHDAY AND ACCOUNT_TYPE = REC.ACCOUNT_TYPE;

			IF V_REGISTERED > 0 THEN
				DBMS_OUTPUT.PUT_LINE('Duplicate Approved Account: ' || REC.FIRSTNAME || ' ' || REC.LASTNAME);
				CONTINUE;
			END IF;

			SELECT NVL(MAX(TO_NUMBER(
				REGEXP_SUBSTR(
				ACCOUNT_NUMBER, '[0-9]+$'))), 0) + 1
			INTO V_NEXT_SEQ
			FROM REGISTEREDINFO;

			V_ACCOUNT_NUMBER :=
				CASE
					WHEN REC.ACCOUNT_TYPE = 'Savings'
						THEN 'SAV'
					ELSE 'CUR'
				END
				||
				UPPER(SUBSTR(RPAD(REPLACE(REC.FIRSTNAME || REC.LASTNAME, ' ', ''), 4, 'X'), 1, 4))
				||
				LPAD(V_NEXT_SEQ, 5, '0');

			INSERT INTO REGISTEREDINFO(
				REQUESTID,
				ACCOUNT_NUMBER,
				BRANCH,
				ACCOUNT_TYPE,
				TITLE,
				FIRSTNAME,
				LASTNAME,
				BIRTHDAY,
				WORKPHONE,
				HOMEPHONE,
				ADDRESS,
				STATE,
				ZIP,
				EMAIL
			) VALUES(
				REC.REQUESTID,
				V_ACCOUNT_NUMBER,
				REC.BRANCH,
				REC.ACCOUNT_TYPE,
				REC.TITLE,
				REC.FIRSTNAME,
				REC.LASTNAME,
				REC.BIRTHDAY,
				REC.WORKPHONE,
				REC.HOMEPHONE,
				REC.ADDRESS,
				REC.STATE,
				REC.ZIP,
				REC.EMAIL
			);

			UPDATE ACCOUNTREQUEST
			SET STATUS = 'Approved'
			WHERE REQUESTID = REC.REQUESTID;

			V_PROCESSED := V_PROCESSED + 1;

		EXCEPTION WHEN OTHERS THEN
			DBMS_OUTPUT.PUT_LINE('Failed RequestID ' || REC.REQUESTID || ': ' || SQLERRM);
		END;
	END LOOP;

	COMMIT;

	DBMS_OUTPUT.PUT_LINE('Approval Batch Completed Successfully.');
	DBMS_OUTPUT.PUT_LINE('Records Processed: ' || V_PROCESSED);

END;
/

