SET SERVEROUTPUT ON;

DECLARE
	V_INSERTED	NUMBER	:= 0;
	V_REJECTED	NUMBER	:= 0;
	V_REASON	VARCHAR2(300);
BEGIN
	DELETE FROM ACCOUNTREQUEST_REJECTED;

	FOR REC IN(SELECT * FROM ACCOUNTREQUEST_STG) LOOP
		V_REASON := NULL;

		IF REC.ACCOUNT_TYPE NOT IN ('Savings', 'Current') THEN
			V_REASON := V_REASON || 'Invalid Account Type; ';
		END IF;

		IF REC.TITLE NOT IN ('Mr', 'Ms', 'Mrs') THEN
			V_REASON := V_REASON || 'Invalid Title; ';
		END IF;

		IF IS_VALID_DATE(REC.BIRTHDAY) = 0 THEN
			V_REASON := V_REASON || 'Invalid Birthday format; ';
		END IF;

		IF NOT REGEXP_LIKE(REC.WORKPHONE, '[0-9]{1,10}$') THEN
			V_REASON := V_REASON || 'Invalid WorkPhone; ';
		END IF;

		IF NOT REGEXP_LIKE(REC.HOMEPHONE, '[0-9]{1,10}$') THEN
			V_REASON := V_REASON || 'Invalid HomePhone; ';
		END IF;

		IF NOT REGEXP_LIKE(REC.ZIP, '[0-9]{1,10}$') THEN
			V_REASON := V_REASON || 'Invalid Zip; ';
		END IF;

		IF V_REASON IS NULL THEN
			INSERT INTO ACCOUNTREQUEST(
				REQUESTID,
				BRANCH,
				ACCOUNT_TYPE,
				TITLE,
				FIRSTNAME,
				LASTNAME,
				BIRTHDAY,
				WORKPHONE,
				HOMEPHONE,
				ADDRESS,
				STATE,
				ZIP,
				EMAIL,
				STATUS
			) VALUES (
				REQ_ID_SEQ.NEXTVAL,
				REC.BRANCH,
				REC.ACCOUNT_TYPE,
				REC.TITLE,
				REC.FIRSTNAME,
				REC.LASTNAME,
				TO_DATE(REC.BIRTHDAY, 'DD/MM/YYYY'),
				TO_NUMBER(REC.WORKPHONE),
				TO_NUMBER(REC.HOMEPHONE),
				REC.ADDRESS,
				REC.STATE,
				TO_NUMBER(REC.ZIP),
				REC.EMAIL,
				'Entered'
			);

			V_INSERTED := V_INSERTED + 1;
		ELSE
			INSERT INTO ACCOUNTREQUEST_REJECTED(
				BRANCH,
				ACCOUNT_TYPE,
				TITLE,
				FIRSTNAME,
				LASTNAME,
				BIRTHDAY,
				WORKPHONE,
				HOMEPHONE,
				ADDRESS,
				STATE,
				ZIP,
				EMAIL,
				REJECT_REASON
			) VALUES(
				REC.BRANCH,
				REC.ACCOUNT_TYPE,
				REC.TITLE,
				REC.FIRSTNAME,
				REC.LASTNAME,
				REC.BIRTHDAY,
				REC.WORKPHONE,
				REC.HOMEPHONE,
				REC.ADDRESS,
				REC.STATE,
				REC.ZIP,
				REC.EMAIL,
				RTRIM(V_REASON, '; ')
			);

			V_REJECTED := V_REJECTED + 1;
		END IF;
	END LOOP;

	COMMIT;

	DBMS_OUTPUT.PUT_LINE('Account Request Batch Completed Successfully.');
	DBMS_OUTPUT.PUT_LINE('Records Inserted: ' || V_INSERTED);
	DBMS_OUTPUT.PUT_LINE('Records Rejected: ' || V_REJECTED);

END;
/
