-- control/transactions.ctl

LOAD DATA
APPEND
INTO TABLE TRANSACTIONINFO_STG
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS(
	TRANSACTIONDATE,
	ACCOUNT_NUMBER,
	AMOUNT,
	TRANSACTION_TYPE
)
