CREATE TABLE TRANSACTIONINFO(
	TRANSACTIONID		NUMBER(10),
	TRANSACTIONDATE		DATE,
	ACCOUNT_NUMBER		VARCHAR2(12),
	AMOUNT			NUMBER(8),
	INTEREST		NUMBER(10,4),
	TRANSACTION_TYPE	VARCHAR2(2),
	CONSTRAINT 		FK_ACCNO	FOREIGN KEY(ACCOUNT_NUMBER)	REFERENCES REGISTEREDINFO(ACCOUNT_NUMBER),
	CONSTRAINT 		CHK_TRANS_TYPE	CHECK(TRANSACTION_TYPE IN ('TR','LN'))
);
