CREATE TABLE ACCOUNTREQUEST(
	REQUESTID 	NUMBER(10),
	BRANCH 		VARCHAR2(15),
	ACCOUNT_TYPE	VARCHAR2(15),
	TITLE		VARCHAR2(4),
	FIRSTNAME	VARCHAR2(15),
	LASTNAME	VARCHAR2(15),
	BIRTHDAY	DATE,
	WORKPHONE	NUMBER(10),
	HOMEPHONE	NUMBER(10),
	ADDRESS		VARCHAR2(30),
	STATE		VARCHAR2(15),
	ZIP		NUMBER(10),
	EMAIL		VARCHAR(30),
	STATUS		VARCHAR(10) DEFAULT 'Entered',
	CONSTRAINT	PK_ACCREQ	PRIMARY KEY(REQUESTID),
	CONSTRAINT	CHK_ACCTYPE	CHECK(ACCOUNT_TYPE IN ('Savings', 'Current')),
	CONSTRAINT 	CHK_TITLE	CHECK(TITLE IN ('Mr', 'Ms', 'Mrs'))
);
