-- database/tables/create_account_request_rejected.sql

CREATE TABLE ACCOUNTREQUEST_REJECTED(
	BRANCH		VARCHAR2(15),
	ACCOUNT_TYPE	VARCHAR2(15),
	TITLE		VARCHAR2(4),
	FIRSTNAME	VARCHAR2(15),
	LASTNAME	VARCHAR2(15),
	BIRTHDAY	VARCHAR2(20),
	WORKPHONE	VARCHAR2(10),
	HOMEPHONE	VARCHAR2(10),
	ADDRESS		VARCHAR2(30),
	STATE		VARCHAR2(15),
	ZIP		VARCHAR2(10),
	EMAIL		VARCHAR2(30),
	REJECT_REASON	VARCHAR2(300),
	REJECT_DATE	DATE	DEFAULT	SYSDATE
);
