CREATE TABLE REGISTEREDINFO(
	REQUESTID	NUMBER(10),
	ACCOUNT_NUMBER	VARCHAR2(12),
	BRANCH		VARCHAR2(15),
	ACCOUNT_TYPE	VARCHAR2(15),
	TITLE		VARCHAR2(4),
	FIRSTNAME	VARCHAR2(15),
	LASTNAME	VARCHAR2(15),
	BIRTHDAY	DATE,
	WORKPHONE	NUMBER(10),
	HOMEPHONE	NUMBER(10),
	ADDRESS		VARCHAR2(30),
	STATE		VARCHAR2(15),
	ZIP		NUMBER(10),
	EMAIL		VARCHAR2(30),
	CONSTRAINT 	PK_ACCNO 	PRIMARY KEY(ACCOUNT_NUMBER),
	CONSTRAINT 	FK_REQID	FOREIGN KEY(REQUESTID)	REFERENCES ACCOUNTREQUEST(REQUESTID)
);
