-- database/functions/fn_calculate_interest.sql

CREATE OR REPLACE FUNCTION CALCULATE_INTEREST(P_AMOUNT NUMBER, P_TRANS_TYPE VARCHAR2)
RETURN NUMBER IS
BEGIN
	IF P_TRANS_TYPE = 'LN' THEN
		RETURN ROUND(P_AMOUNT * 0.10, 4);
	END IF;

	RETURN 0;
END;
/

