-- database/functions/fn_is_valid_date.sql

CREATE OR REPLACE FUNCTION IS_VALID_DATE(P_DATE VARCHAR2)
RETURN NUMBER IS
	V_DATE DATE;
BEGIN
	IF NOT REGEXP_LIKE(P_DATE, '[0-9]{2}/[0-9]{2}/[0-9]{4}$') THEN
		RETURN 0;
	END IF;

	V_DATE := TO_DATE(P_DATE, 'DD/MM/YYYY');

	IF TO_CHAR(V_DATE, 'DD/MM/YYYY') = P_DATE THEN
		RETURN 1;
	ELSE
		RETURN 0;
	END IF;

EXCEPTION WHEN OTHERS THEN
	RETURN 0;
END;
/
